### ISSUE TITLE
Incompatible with folders plugin ?

### ISSUE THREAD

**Issue by aacebedo** [jenkinsci/depbuilder-plugin#1]
Execution of jobs stored in folders created with the cloudbees-folders plugin fails.

An error about not finding the job is returned.

**Comment by RoyalSloth** [comment]
Thanks for the report.

It looks like the job is parsed correctly if you put it into quotes: "myFolder/myJob", but then it fails later when it should be scheduled and built.

Since I am not that familiar with the folder plugin, I am wondering what exactly is your use case here? Do you use the folder just as a namespace for your jobs (to make navigating UI easier), or do you use it as a group of jobs that should always be executed together (e.g: a folder is a parent job that builds all its children)?

**Comment by aacebedo** [comment]
Hi !

I use folders as a namespace to organize the UI easily.
I saw that the " removes the parsing error but yes the execution fails
anyway



Le mer. 10 févr. 2021 à 11:05, RoyalSloth <notifications@github.com> a
écrit :

**Comment by aacebedo** [comment]
Hi !

I use folders as a namespace to organize the UI easily.
I saw that the " removes the parsing error but yes the execution fails
anyway

**Comment by RoyalSloth** [comment]
This bug should be fixed with the latest version - 1.0.6.

It usually takes a few hours before the version appears in the marketplace, but you can test it right away by manually uploading the hpi file: https://github.com/jenkinsci/depbuilder-plugin/releases/tag/depbuilder-1.0.6

**Comment by aacebedo** [comment]
Great thank you.
I'll try that ASAP
